language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ioannisid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ioannisid/docker-react npm run test